// examples/vue/src/components/MoleculeStructure.vue
<template>

    <p v-if="rdkitError">Error loading renderer</p>

    <p v-if="!rdkitLoaded">Loading renderer</p>

    <span v-else-if="!isValidMolString(structure)" :title="`Cannot render structure: ${structure}`"></span>

    <div 
        v-else-if="svgMode"
        :class="`molecule-structure-svg ${className}`"
        :style="{width: props.width, height: props.height}"
        v-html="svg"
    ></div>

    <div v-else :class="`molecule-canvas-container ${className}`">
        <canvas :title="structure" :id="id" :width="width" :height="height"></canvas>
    </div>

</template>

<script setup lang="ts">
import { onMounted, onUpdated, reactive, ref, watch } from 'vue';
import { JSMol } from '../../../../typescript';
import initRDKit from '../utils/initRDKit';

const props = defineProps({
    /**
     * Generic props
     */
    id: {
        type: String,
        required: true
    },
    className: {
        type: String,
        default: ""
    },
    svgMode: {
        type: Boolean,
        default: false
    },
    width: {
        type: Number,
        default: 250
    },
    height: {
        type: Number,
        default: 200
    },
    /**
     * RDKit-specific props
     */
    structure :{
        type: String,
        required: true
    },
    subStructure: {
        type: String,
        default: ""
    },
    extraDetails: {
        type: Object,
        default:  {}
    },
    drawingDelay: {
        type: Number,
        default: undefined
    }
})

// RDKit state reporting values
let rdkitLoaded = ref(false)
let rdkitError = ref(false)

// Molecule state values
let wasCalled = ref(false)
let molDetails = reactive({
    width: props.width,
    height: props.height,
    bondLineWidth: 1,
    addStereoAnnotation: true,
    ...props.extraDetails
})
let svg = ref('')

/**
 * Validate the molecule
 */
function isValid(m: JSMol)
{
    return !!m && m.is_valid()
}

/**
 * Validate the string representation of the molecule
 */
function isValidMolString(s: string)
{
    const mol = window.RDKit.get_mol(s || "invalid")
    const isValidMol = isValid(mol)
    mol.delete()

    return isValidMol
}

/** 
 * Get highlight details for molecule
 */
function getMolDetails(mol: JSMol, qmol: JSMol)
{
    if (isValid(mol) && isValid(qmol))
    {
        // get substructure highlight details
        const details = JSON.parse(mol.get_substruct_matches(qmol))
        // reduce the list of objects to a single list object with all atoms and bonds
        const detailsMerged: { atoms: number[], bonds: number[] } = details ? details.reduce( (acc: { atoms: number[], bonds: number[] }, { atoms, bonds }: {atoms: number[], bonds: number[]}) => ({
                atoms: [...acc.atoms, ...atoms],
                bonds: [...acc.bonds, ...bonds]
            }), { atoms: [], bonds: [] } 
        ) : details

        return JSON.stringify({
            ...molDetails,
            ...(props.extraDetails || {}),
            ...detailsMerged
        })
    }
    else
    {
        // if one of the molecules are not valid, return no highlight details
        return JSON.stringify({
            ...molDetails,
            ...(props.extraDetails || {})
        })
    }
}


/**
 * Draw the molecule to the canvas, or return set the SVG variable
 */
function drawSVGorCanvas()
{
    const mol = window.RDKit.get_mol(props.structure || "invalid")
    const qmol = window.RDKit.get_qmol(props.subStructure || "invalid")
    const isValidMol = isValid(mol)

    if (props.svgMode && isValidMol)
    {
        const svgGenerated = mol.get_svg_with_highlights(getMolDetails(mol, qmol))
        svg.value = svgGenerated
    }
    else if (isValidMol)
    {
        const canvas = document.getElementById(props.id) as HTMLCanvasElement
        mol.draw_to_canvas_with_highlights(canvas, getMolDetails(mol, qmol))
    }

    /**
     * Delete C++ mol objects manually
     * https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-management
     */
    mol.delete()
    qmol.delete()
}

/** 
 * Calls the main drawing logic, either with a delay or without
 */
function draw()
{
    if (props.drawingDelay)
    {
        setTimeout(() => drawSVGorCanvas(), props.drawingDelay)
    }
    else
    {
        drawSVGorCanvas()
    }
}

/**
 * Ensures draw() is only called once
 */
function drawOnce()
{
    return () => {
        if (wasCalled.value === false)
        {
            wasCalled.value = true
            draw()
        }
    }
}

/**
 * Load molecule on component mount
 */
onMounted(() => {
    initRDKit()
    .then(() => {
        rdkitLoaded.value = true
        try
        {
            draw()
        }
        catch(err)
        {
            console.error(err)
        }
    })
    .catch((err) => {
        console.error(err)
        rdkitError.value = true
    })
})

/**
 * Redraw molecule on component update, or props changes
 */

onUpdated(() => {
    if (!rdkitError && rdkitLoaded && !props.svgMode)
    {
        //drawOnce()
    }
})

//watch([props.structure, props.subStructure, props.svgMode, props.width, props.height, props.extraDetails], () => draw())

</script>

<style>

.molecule-structure-svg svg rect:first-of-type {
  fill: transparent !important;
}

</style>

// examples/react/src/components/MoleculeStructure/MoleculeStructure.js
import React, { Component } from "react";
import _ from "lodash";
import PropTypes from "prop-types";
import "./MoleculeStructure.css";
import initRDKit from "../../utils/initRDKit";

class MoleculeStructure extends Component {
  static propTypes = {
    /**
     * Generic properties
     */
    id: PropTypes.string.isRequired,
    className: PropTypes.string,
    svgMode: PropTypes.bool,
    width: PropTypes.number,
    height: PropTypes.number,
    /**
     * RDKit-specific properties
     */
    structure: PropTypes.string.isRequired,
    subStructure: PropTypes.string,
    extraDetails: PropTypes.object,
    drawingDelay: PropTypes.number
  };

  static defaultProps = {
    subStructure: "",
    className: "",
    width: 250,
    height: 200,
    svgMode: false,
    extraDetails: {},
    drawingDelay: undefined
  };

  constructor(props) {
    super(props);

    this.MOL_DETAILS = {
      width: this.props.width,
      height: this.props.height,
      bondLineWidth: 1,
      addStereoAnnotation: true,
      ...this.props.extraDetails
    };

    this.state = {
      svg: undefined,
      rdKitLoaded: false,
      rdKitError: false
    };
  }

  drawOnce = (() => {
    let wasCalled = false;

    return () => {
      if (!wasCalled) {
        wasCalled = true;
        this.draw();
      }
    };
  })();

  draw() {
    if (this.props.drawingDelay) {
      setTimeout(() => {
        this.drawSVGorCanvas();
      }, this.props.drawingDelay);
    } else {
      this.drawSVGorCanvas();
    }
  }

  drawSVGorCanvas() {
    const mol = window.RDKit.get_mol(this.props.structure || "invalid");
    const qmol = window.RDKit.get_qmol(this.props.subStructure || "invalid");
    const isValidMol = this.isValidMol(mol);

    if (this.props.svgMode && isValidMol) {
      const svg = mol.get_svg_with_highlights(this.getMolDetails(mol, qmol));
      this.setState({ svg });
    } else if (isValidMol) {
      const canvas = document.getElementById(this.props.id);
      mol.draw_to_canvas_with_highlights(canvas, this.getMolDetails(mol, qmol));
    }

    /**
     * Delete C++ mol objects manually
     * https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-management
     */
    mol.delete();
    qmol.delete();
  }

  isValidMol(mol) {
    return !!mol && mol.is_valid();
  }

  getMolDetails(mol, qmol) {
    if (this.isValidMol(mol) && this.isValidMol(qmol)) {
      const subStructHighlightDetails = JSON.parse(
        mol.get_substruct_matches(qmol)
      );
      const subStructHighlightDetailsMerged = !_.isEmpty(
        subStructHighlightDetails
      )
        ? subStructHighlightDetails.reduce(
            (acc, { atoms, bonds }) => ({
              atoms: [...acc.atoms, ...atoms],
              bonds: [...acc.bonds, ...bonds]
            }),
            { bonds: [], atoms: [] }
          )
        : subStructHighlightDetails;
      return JSON.stringify({
        ...this.MOL_DETAILS,
        ...(this.props.extraDetails || {}),
        ...subStructHighlightDetailsMerged
      });
    } else {
      return JSON.stringify({
        ...this.MOL_DETAILS,
        ...(this.props.extraDetails || {})
      });
    }
  }

  componentDidMount() {
    initRDKit()
      .then(() => {
        this.setState({ rdKitLoaded: true });
        try {
          this.draw();
        } catch (err) {
          console.log(err);
        }
      })
      .catch((err) => {
        console.log(err);
        this.setState({ rdKitError: true });
      });
  }

  componentDidUpdate(prevProps) {
    if (
      !this.state.rdKitError &&
      this.state.rdKitLoaded &&
      !this.props.svgMode
    ) {
      this.drawOnce();
    }

    if (this.state.rdKitLoaded) {
      const shouldUpdateDrawing =
        prevProps.structure !== this.props.structure ||
        prevProps.svgMode !== this.props.svgMode ||
        prevProps.subStructure !== this.props.subStructure ||
        prevProps.width !== this.props.width ||
        prevProps.height !== this.props.height ||
        !_.isEqual(prevProps.extraDetails, this.props.extraDetails);

      if (shouldUpdateDrawing) {
        this.draw();
      }
    }
  }

  render() {
    if (this.state.rdKitError) {
      return "Error loading renderer.";
    }
    if (!this.state.rdKitLoaded) {
      return "Loading renderer...";
    }

    const mol = window.RDKit.get_mol(this.props.structure || "invalid");
    const isValidMol = this.isValidMol(mol);
    mol.delete();

    if (!isValidMol) {
      return (
        <span title={`Cannot render structure: ${this.props.structure}`}>
          Render Error.
        </span>
      );
    } else if (this.props.svgMode) {
      return (
        <div
          title={this.props.structure}
          className={"molecule-structure-svg " + (this.props.className || "")}
          style={{ width: this.props.width, height: this.props.height }}
          dangerouslySetInnerHTML={{ __html: this.state.svg }}
        ></div>
      );
    } else {
      return (
        <div
          className={
            "molecule-canvas-container " + (this.props.className || "")
          }
        >
          <canvas
            title={this.props.structure}
            id={this.props.id}
            width={this.props.width}
            height={this.props.height}
          ></canvas>
        </div>
      );
    }
  }
}

export default MoleculeStructure;
