// examples/angular/src/app/examples/introduction/introduction.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-introduction",
  templateUrl: "./introduction.component.html",
  styleUrls: ["./introduction.component.css"]
})
export class IntroductionComponent {}

<div id="component-introduction" class="container">
    <section class="hero">
        <div class="hero-body">
            <h1 class="title">Introduction</h1>
            <p class="subtitle column is-two-thirds pl-0">
                Welcome to RDKit.js for Angular. If you didn't do it already, we
                first recommend to go through the
                <a href="https://rdkitjs.com#drawing-molecules-all-options">
                    JavaScript examples
                </a>
                for a low-level overview of the RDKit.js API.
            </p>
        </div>
    </section>
</div>

// examples/vue/src/components/Introduction.vue
<template>
    <div id="component-introduction" class="container">
        <section class="hero">
            <div class="hero-body">
            <p class="title">Introduction</p>
            <p class="subtitle column is-two-thirds pl-0">
                Welcome to RDKit.js for React. If you didn't do it already, we
                first recommend to go through the
                <a href="https://rdkitjs.com#drawing-molecules-all-options">
                JavaScript examples
                </a>
                for a low-level overview of the RDKit.js API.
            </p>
            </div>
        </section>
    </div>
</template>
