// examples/vue/src/components/examples/ExampleMultiSubstructure.vue
<template>
    <div id="component-example-multi-substruct" class="container">
      <section class="hero">
        <div class="hero-body">
          <p class="title">Multi-substructure Highlight</p>
          <p class="subtitle">
            You can also highlight multiple substructures of molecules with
            SMILES, SMARTS and a combination of the two with dot notation.
          </p>
        </div>
      </section>
      <div class="columns is-desktop">
        <div class="column" v-for="({mol, qmol}, idx) in molecules">
          <MoleculeStructure
            :id="`structure-example-multisubstruct-svg-${idx}`"
            :structure=mol
            :subStructure=qmol
            :width="350"
            :height="300"
            svgMode
          />
        </div>
      </div>
    </div>
</template>

<script setup lang="ts">
import MoleculeStructure from '../MoleculeStructure.vue';

const molecules = [
    {
        mol: "CN1C=NC2=C1C(=O)N(C(=O)N2C)",
        qmol: "[N,n,o,O]"
    },
    {
        mol: "CC(=O)Oc1ccccc1C(=O)O",
        qmol: "[O,o].c1ccccc1"
    }
]
</script>

// examples/react-example/src/examples/ExampleMultiSubstructure.js
import MoleculeStructure from "../components/MoleculeStructure/MoleculeStructure";

function ExampleMultiSubstructure() {
  const caffeine = "CN1C=NC2=C1C(=O)N(C(=O)N2C)";
  const caffeineSubStruct = "[N,n,o,O]";

  const aspirin = "CC(=O)Oc1ccccc1C(=O)O";
  const aspirinSubStruct = "[O,o].c1ccccc1";

  return (
    <div id="component-example-multi-substruct" className="container">
      <section className="hero">
        <div className="hero-body">
          <p className="title">Multi-substructure Highlight</p>
          <p className="subtitle">
            You can also highlight multiple substructures of molecules with
            SMILES, SMARTS and a combination of the two with dot notation.
          </p>
        </div>
      </section>
      <div className="columns is-desktop">
        <div className="column">
          <MoleculeStructure
            width={350}
            height={300}
            svgMode
            structure={caffeine}
            subStructure={caffeineSubStruct}
            id="structure-example-multisubstruct-svg-caffeine"
          />
        </div>
        <div className="column">
          <MoleculeStructure
            width={350}
            height={300}
            structure={aspirin}
            subStructure={aspirinSubStruct}
            id="structure-example-multisubsctruct-canvas-aspirin"
          />
        </div>
      </div>
    </div>
  );
}

export default ExampleMultiSubstructure;
