// examples/vue/src/components/examples/ExampleList.vue
<template>
    <div id="component-example-list" class="container">
        <section class="hero">
            <div class="hero-body">
                <p class="title">Overview</p>
                <p class="subtitle">You can draw any molecule from SMILES dynamically with RDKit.js.</p>
            </div>
        </section>
        <div id="structure-list" class="columns is-desktop">
            <div class="column" v-for="smiles in SMILES_LIST">
                <MoleculeStructure :id="smiles" :structure="smiles" :height="200" :width="200" svg-mode></MoleculeStructure>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import MoleculeStructure from '../MoleculeStructure.vue';
import { SMILES_LIST } from '../../utils/smiles';
</script>

<style scoped>

#structure-list {
    margin: 12px;
    overflow-x: scroll;
}

</style>

// examples/react/src/examples/ExampleList.js
import React from "react";
import MoleculeStructure from "../components/MoleculeStructure/MoleculeStructure";
import { SMILES_LIST } from "../utils/smiles";

class ExampleList extends React.Component {
  render() {
    return (
      <div id="component-example-list" className="container">
        <section className="hero">
          <div className="hero-body">
            <p className="title">Overview</p>
            <p className="subtitle">
              You can draw any molecule from SMILES dynamically with rdkit.js .
            </p>
          </div>
        </section>
        <div
          id="structure-list"
          className="columns is-desktop"
          style={{ margin: "12px", overflowX: "scroll" }}
        >
          {SMILES_LIST.map((smiles) => (
            <div className="column" key={smiles}>
              <MoleculeStructure
                id={smiles}
                structure={smiles}
                height={200}
                width={200}
                svgMode
              />
            </div>
          ))}
        </div>
      </div>
    );
  }
}

export default ExampleList;
