// examples/react/src/examples/ExampleSubstructureSearch.js
import React from "react";
import _ from "lodash";
import MoleculeStructure from "../components/MoleculeStructure/MoleculeStructure";
import { SMILES_LIST } from "../utils/smiles";

class ExampleList extends React.Component {
  state = {
    matches: SMILES_LIST,
    searchValue: "",
    searching: false
  };

  render() {
    const matches = this.state.matches.slice(0, 50);
    return (
      <div id="component-example-substruct-search" className="container">
        <section className="hero">
          <div className="hero-body">
            <p className="title">Substructure match</p>
            <p className="subtitle">
              You can perform client-side substructure match.
            </p>
          </div>
        </section>
        <div className="columns" style={{ margin: "12px 0" }}>
          <div className="column">
            <div className="field">
              <div className="control has-icons-left">
                <input
                  className="input"
                  type="email"
                  onChange={(e) => this.handleSearchChange(e)}
                  placeholder="Enter a SMARTS or SMILES string here..."
                />
                {this.renderInputIcon()}
              </div>
            </div>
          </div>
        </div>
        <div className="columns is-multiline" style={{ margin: "12px" }}>
          {matches.length > 0
            ? matches.slice(0, 40).map((smiles) => (
                <div className="column" key={smiles}>
                  <MoleculeStructure
                    id={smiles}
                    structure={smiles}
                    subStructure={this.state.searchValue}
                    height={200}
                    width={200}
                    svgMode
                  />
                </div>
              ))
            : "Input is either invalid or no matches were found."}
        </div>
      </div>
    );
  }

  handleSearchChange = _.debounce((e) => {
    this.setState({ searching: true });

    setTimeout(() => {
      const noMatchLength = 2;
      const currentVal = e.target.value;
      this.setState({ searchValue: currentVal });
      if (!currentVal) {
        this.setState({ matches: SMILES_LIST.slice(), searching: false });
      } else {
        const qmol = window.RDKit.get_qmol(currentVal);
        if (!this.isValidMol(qmol)) {
          this.setState({ matches: [], searching: false });
        } else {
          const matches = SMILES_LIST.filter((smiles) => {
            const mol = window.RDKit.get_mol(smiles);
            const hasMatch = mol.get_substruct_match(qmol).length > noMatchLength;
            mol?.delete();
            return hasMatch;
          });
          this.setState({ matches, searching: false });
          qmol?.delete();
        }
      }
    }, 100);
  }, 300);

  renderInputIcon() {
    if (this.state.searching) {
      return (
        <span key="searching-input-icon" className="icon is-small is-left">
          <i className="fas fa-circle-notch fa-spin" />
        </span>
      );
    } else {
      return (
        <span key="search-input-icon" className="icon is-small is-left">
          <i className="fas fa-search" />
        </span>
      );
    }
  }

  isValidMol(qmolOrMol) {
    return !!qmolOrMol;
  }
}

export default ExampleList;

// examples/vue/src/components/examples/ExampleSubstructureSearch.vue
<template>
  <div id="component-example-substruct-search" class="container">
    <section class="hero">
      <div class="hero-body">
        <p class="title">Substructure match</p>
        <p class="subtitle">You can perform client-side substructure match.</p>
      </div>
    </section>
    <div class="columns" :style="{ margin: '12px 0' }">
      <div class="column">
        <div class="field">
          <div class="control has-icons-left">
            <input
              class="input"
              type="email"
              placeholder="Enter a SMARTS or SMILES string here..."
              v-model="searchValue"
            />
            <span key="search-input-icon" class="icon is-small is-left">
              <i
                :class="
                  searching ? 'fas fa-circle-notch fa-spin' : 'fas fa-search'
                "
              ></i>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="columns is-multiline" :style="{ margin: '12px' }">
      <template v-if="matches.length > 0">
        <div class="column" v-for="smiles in matches">
          <MoleculeStructure
            :id="smiles"
            :structure="smiles"
            :subStructure="searchValue"
            :height="200"
            :width="200"
            svg-mode
          ></MoleculeStructure>
        </div>
      </template>
      <p v-else>Input is either invalid or no matches were found.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import MoleculeStructure from "../MoleculeStructure.vue";
import { SMILES_LIST } from "../../utils/smiles";
import { reactive, ref, watch } from "vue";
import debounce from "debounce";

let searching = ref(false);
let searchValue = ref("");
let matches = reactive<string[]>([...SMILES_LIST]);

const noMatchLength = 2;

function updateMatches(list: string[]) {
  matches.length = 0;
  matches.push(...list);
}

function performSearch() {
  // start search
  searching.value = true;

  if (!searchValue.value) {
    searching.value = false;
    updateMatches(SMILES_LIST);
    return;
  }

  const qmol = window.RDKit.get_qmol(searchValue.value);

  const results = SMILES_LIST.filter((smiles: string) => {
    // only return those from the list that match the query
    const mol = window.RDKit.get_mol(smiles);
    const hasMatch = mol.get_substruct_match(qmol).length > noMatchLength;
    mol?.delete();
    return hasMatch;
  });

  qmol?.delete();

  // replace search results
  updateMatches(results);

  // finish search
  searching.value = false;
}

const debouncedSearch = debounce(performSearch, 300);

watch(searchValue, debouncedSearch);
</script>
