// examples/react-example/src/examples/ExampleMoleculeStructure.js
function ExampleMoleculeStructure() {
  return (
    <div id="component-example-svg" className="container">
      <section className="hero">
        <div className="hero-body">
          <p className="title">MoleculeStructure</p>
          <p className="subtitle">
            The examples below will mostly use the React component{" "}
            <code className="is-family-code">MoleculeStructure</code> to render
            the examples. You can see the React implementation in the code
            below.
          </p>
        </div>
      </section>
    </div>
  );
}

export default ExampleMoleculeStructure;

// examples/vue/src/components/examples/ExampleMoleculeStructure.vue
<template>
  <div id="component-example-moleculestructure" class="container">
    <section class="hero">
      <div class="hero-body">
        <p class="title">MoleculeStructure</p>
        <p class="subtitle">
          The examples below will mosty use the Vue component
          <code class="is-family-code">MoleculeStructure</code>
          to render the examples. You can see the Vue implementation in the code
          below.
        </p>
      </div>
    </section>
  </div>
</template>
